io.mend.sast.exception.UserNotFoundException#instance-init#