io.mend.sast.exception.UserNotFoundException#<init>()V