io.mend.sast.exception.AnotherException#instance-init#